[tox]
envlist =
  py310-neuron{8},
  py311-neuron{8},
  py312-neuron{9},
  py313-neuron{9},
  py314-neuron{9},
  coverage

[testenv]
extras = dev
deps =
  neuron8: neuron>=8,<9
  neuron9: neuron>=9,<10

commands =
    python --version
    pyfibers_compile
    coverage run -m pytest tests/unit
    pytest tests/integration

[testenv:coverage]
basepython =
    python3

commands =
    coverage combine
    coverage report
    coverage xml
    coverage html

depends =
    py310
    py311
    py312
    py313
    py314
